//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnHK3_4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Payments = new HashSet<Payment>();
            this.Sendings = new HashSet<Sending>();
        }
        [DisplayName("Account Id")]
        public int id { get; set; }
        [Required(ErrorMessage = "Username Can not Empty")]
        [DisplayName("UserName")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string username { get; set; }
        [Required(ErrorMessage = "Password Can not Empty")]
        [StringLength(30, MinimumLength = 8, ErrorMessage = "8-30 characters")]
        [DataType(DataType.Password)]
        [DisplayName("Password")]
        public string password { get; set; }
        [DisplayName("Question")]
        public string question { get; set; }
        [Required(ErrorMessage = "Answer Can not Empty")]
        [StringLength(25, MinimumLength = 2, ErrorMessage = "2-25 characters")]
        [DisplayName("Answer")]
        public string answer { get; set; }
        [DisplayName("Role Name")]
        public int roldId { get; set; }
        [DisplayName("Facebook")]
        public Nullable<bool> facebook { get; set; }
        [DisplayName("FirstName")]
        [RegularExpression("^([a-zA-Z0-9 .&'-]+)$", ErrorMessage = "Can't have numer in FirstName")]
        public string firstName { get; set; }
        [DisplayName("LastName")]
        [RegularExpression("^([a-zA-Z0-9 .&'-]+)$", ErrorMessage = "Can't have numer in LastName")]
        public string lastName { get; set; }
        [DisplayName("Gender")]
        public string gender { get; set; }
        [DisplayName("Address")]
        public string address { get; set; }
        [DisplayName("Country")]
        public string country { get; set; }
        [DisplayName("Mobile")]
        [RegularExpression(@"^\+?\d{1,3}?[- .]?\(?(?:\d{2,3})\)?[- .]?\d\d\d[- .]?\d\d\d\d$", ErrorMessage = "Phone number is malformed")]

        public string mobile { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sending> Sendings { get; set; }
    }
}
