//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnHK3_4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Greeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Greeting()
        {
            this.Sendings = new HashSet<Sending>();
        }
        [Display(Name = "Greeting ID")]
        public int id { get; set; }
        [Display(Name = "Photo")]
        [Required(ErrorMessage = "Please Input Photo")]
        public string photo { get; set; }
        public Nullable<int> categoryDetailsID { get; set; }
        [Display(Name = "Video")]
        public string video { get; set; }
        public string url { get; set; }
    
        public virtual Category_Details Category_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sending> Sendings { get; set; }
    }
}
