//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnHK3_4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Payment
    {
        [DisplayName("Account ID")]
        public int accountId { get; set; }
        [DisplayName("Service ID")]
        public int serviceId { get; set; }
        [DisplayName("Amount")]
        public Nullable<decimal> amount { get; set; }
        [DisplayName("Expiry Date")]
        public Nullable<System.DateTime> expiryDate { get; set; }
        [DisplayName("Payment Number")]
        public Nullable<int> paymentNumber { get; set; }
        [DisplayName("Status")]
        public Nullable<bool> Status { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Service Service { get; set; }
    }
}
