//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnHK3_4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Sending
    {
        [DisplayName("Greeting Id")]
        public int greetingId { get; set; }
        [DisplayName("Account Id")]
        public int AccountId { get; set; }
        [DisplayName("Sender Name")]
        public string senderName { get; set; }
        [DisplayName("Rersive Name")]
        public string rersiveName { get; set; }
        [DisplayName("Address To")]
        public string addressTo { get; set; }
        [DisplayName("Custom Messenger")]
        public string customMessenger { get; set; }
        [DisplayName("Sending ID")]
        public int id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Greeting Greeting { get; set; }
    }
}
